"""
Pydantic v2 data models for the Research Intelligence and Benchmarking Assistant.

All models use Pydantic v2 for schema validation and serialization.
Serialization is performed via model.model_dump_json() and
deserialization via Model.model_validate_json() to guarantee round-trip integrity.
"""

from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import Literal

from pydantic import BaseModel, Field, HttpUrl


class SourceType(str, Enum):
    """Type of source: patent or scientific paper."""
    PATENT = "patent"
    PAPER = "paper"


class ConfidenceLevel(str, Enum):
    """Confidence level in extracted information quality."""
    HIGH = "High"
    MEDIUM = "Medium"
    LOW = "Low"


class CoverageValue(float, Enum):
    """Coverage value for benchmark metric scoring."""
    COVERED = 1.0
    PARTIAL = 0.5
    NOT_COVERED = 0.0


class SearchQuery(BaseModel):
    """
    A search query submitted to a data source.

    Tracks the query string, source name, and execution timestamp
    for traceability and debugging.
    """
    query_string: str
    source: str
    timestamp: datetime = Field(default_factory=datetime.utcnow)


class RawSourceItem(BaseModel):
    """
    A single source item collected from a search adapter.

    Represents the raw data extracted from patents or scientific papers
    before relevance scoring or deduplication.
    """
    title: str
    source_type: SourceType
    source_url: str
    publication_date: str | None = None
    author_or_assignee: str | None = None
    relevance_explanation: str | None = None
    confidence_level: ConfidenceLevel | None = None
    doi: str | None = None
    patent_number: str | None = None
    raw_adapter_source: str  # which adapter produced this item


class ScoredSourceItem(RawSourceItem):
    """
    A source item with a computed relevance score.

    Extends RawSourceItem by adding a relevance score between 0.0 and 1.0,
    computed by the ranking engine using LLM-assisted scoring.
    """
    relevance_score: float = Field(ge=0.0, le=1.0)


class RankedResults(BaseModel):
    """
    The top-ranked papers and patents after scoring and selection.

    Contains exactly 3 papers and 3 patents after the ranking stage,
    sorted by descending relevance score.
    """
    papers: list[ScoredSourceItem]
    patents: list[ScoredSourceItem]


class BenchmarkMetric(BaseModel):
    """
    A single benchmark criterion for evaluating sources.

    Metrics are generated by the LLM based on the research topic
    and are used to score sources in the benchmark table.
    """
    name: str
    description: str | None = None
    category: str | None = None


class CoverageCell(BaseModel):
    """
    A single cell in the benchmark scoring matrix.

    Represents the coverage value (Covered/Partial/Not Covered) for
    a specific source item against a specific benchmark metric.
    """
    source_item_title: str
    metric_name: str
    value: CoverageValue
    rationale: str | None = None


class BenchmarkScores(BaseModel):
    """
    Complete benchmark scoring data for all sources and metrics.

    Contains all coverage cells and provides a method to compute
    the final score for each source item.
    """
    cells: list[CoverageCell]

    def final_score(self, source_title: str, metrics: list[BenchmarkMetric]) -> float:
        """
        Compute the final score for a source item.

        Final score = sum(coverage_values) / number_of_metrics,
        rounded to 2 decimal places.

        Args:
            source_title: Title of the source item to score
            metrics: List of all benchmark metrics being evaluated

        Returns:
            Final score between 0.0 and 1.0 (or 0.0 if no metrics)
        """
        values = [
            c.value for c in self.cells
            if c.source_item_title == source_title
        ]
        return round(sum(values) / len(metrics), 2) if metrics else 0.0


class ApprovedState(BaseModel):
    """
    The user-approved sources and metrics after validation.

    Represents the final state after the interactive validation step,
    including all approved papers, patents, and benchmark metrics.
    This is the input to the report generation stage.
    """
    topic: str
    papers: list[ScoredSourceItem]
    patents: list[ScoredSourceItem]
    metrics: list[BenchmarkMetric]
    confirmed_at: datetime = Field(default_factory=datetime.utcnow)


class HistoryEntry(BaseModel):
    """
    A record of a completed research workspace.

    Tracks metadata for each generated report, enabling users to
    revisit, update, or regenerate previous reports.
    """
    topic: str
    creation_date: datetime
    last_updated: datetime
    report_version: int = 1
    paper_count: int
    patent_count: int
    report_file_path: str
    workspace_dir: str


class OrchestratorResult(BaseModel):
    """
    The output of the search orchestration stage.

    Contains the research topic, all search queries executed,
    and all raw source items collected from all adapters.
    """
    topic: str
    queries: list[SearchQuery]
    raw_items: list[RawSourceItem]
